In [7]:
import numpy as np


In [8]:
# in python
a=[1,2,3,4,5]
b=[6,7,8,9,10]
sum=a+b
print(sum)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
# using numpy
a_new=np.array([1,2,3,4,5])
b_new=np.array([6,7,8,9,10])
sum_new=a_new+b_new
print(sum_new)

[ 7  9 11 13 15]


In [10]:
# nested list
x=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.shape(x)

(3, 3)

In [12]:
# range function
# in python
list=[]
for x in range(15):
    list.append(x)
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [13]:
# using numpy
list_new=np.arange(15)
list_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# list comprehensions
list=[x**2 for x in range(15)]
print(list)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]


In [15]:
d=[f+2 for f in range(7)]
d

[2, 3, 4, 5, 6, 7, 8]

In [16]:
# performance measurement(%timeit)
g=range(10**3)
%timeit [y**2 for y in g] 

436 µs ± 25.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
g_new=np.arange(10**3)
%timeit g_new**2

1.99 µs ± 91.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
# creating numpy array
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [19]:
np.arange(3,14)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [20]:
np.arange(5,12,2)

array([ 5,  7,  9, 11])

In [21]:
np.arange(1500,200,-300)

array([1500, 1200,  900,  600,  300])

In [22]:
# matrices
# null matrix
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.zeros([5,5],dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# nested list to matrix
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# creating null matrix of shape z(above matrix)
np.zeros_like(z)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
# unit matrix
np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
# identity mtrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# full
np.full([6,4],2.32,dtype=np.int32)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [29]:
# diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
# tile function
p=np.array([1,2,3,4])
p

array([1, 2, 3, 4])

In [31]:
np.tile(p,(3,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [32]:
q=np.array([[10,20,30],[40,50,60]])
q

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
np.tile(q,(3,3))

array([[10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60]])

In [34]:
# random no.
np.random.random(10)

array([0.31293581, 0.43430122, 0.19181184, 0.07930252, 0.62233986,
       0.93086511, 0.44653429, 0.2222944 , 0.38853383, 0.55666631])

In [35]:
np.random.random(10)

array([0.04611908, 0.87944126, 0.53911952, 0.30280214, 0.00268285,
       0.5311888 , 0.63507902, 0.84469002, 0.57810085, 0.36873245])

In [36]:
np.random.seed(123)
print(np.random.random())

0.6964691855978616


In [51]:
np.random.seed(123)
print(np.random.random())

0.6964691855978616


In [38]:
# round fn
z=np.random.random([4,3])
z

array([[0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802],
       [0.72904971, 0.43857224, 0.0596779 ]])

In [39]:
# round function
np.round(z,3)

array([[0.227, 0.551, 0.719],
       [0.423, 0.981, 0.685],
       [0.481, 0.392, 0.343],
       [0.729, 0.439, 0.06 ]])

In [40]:
# to get only integer value or only float value(astype)
xyz=np.random.random([4,4])
xyz


array([[0.39804426, 0.73799541, 0.18249173, 0.17545176],
       [0.53155137, 0.53182759, 0.63440096, 0.84943179],
       [0.72445532, 0.61102351, 0.72244338, 0.32295891],
       [0.36178866, 0.22826323, 0.29371405, 0.63097612]])

In [41]:
xyz_1=xyz*100
xyz_1


array([[39.80442553, 73.79954057, 18.24917305, 17.54517561],
       [53.15513738, 53.18275871, 63.44009586, 84.94317941],
       [72.44553249, 61.10235107, 72.24433826, 32.29589139],
       [36.17886556, 22.82632309, 29.37140464, 63.09761239]])

In [42]:
xyz_2=xyz_1.astype(np.float32)
xyz_2

array([[39.804424, 73.79954 , 18.249172, 17.545176],
       [53.155136, 53.18276 , 63.440094, 84.94318 ],
       [72.44553 , 61.102352, 72.24434 , 32.29589 ],
       [36.178867, 22.826323, 29.371405, 63.097614]], dtype=float32)

In [43]:
xyz_2=xyz_1.astype(np.int32)
xyz_2

array([[39, 73, 18, 17],
       [53, 53, 63, 84],
       [72, 61, 72, 32],
       [36, 22, 29, 63]])

In [44]:
# second session on numpy
# reshaping
l=np.array([[12,13,14,15],[15,16,17,18],[18,19,20,21]])
print(l)
l.shape

[[12 13 14 15]
 [15 16 17 18]
 [18 19 20 21]]


(3, 4)

In [45]:
l.reshape(1,-1)


array([[12, 13, 14, 15, 15, 16, 17, 18, 18, 19, 20, 21]])

In [46]:
l.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [15],
       [16],
       [17],
       [18],
       [18],
       [19],
       [20],
       [21]])

In [47]:
l.reshape(2,-3)

array([[12, 13, 14, 15, 15, 16],
       [17, 18, 18, 19, 20, 21]])

In [48]:
l.reshape(-1,4)

array([[12, 13, 14, 15],
       [15, 16, 17, 18],
       [18, 19, 20, 21]])

In [49]:
l.reshape(6,-3)

array([[12, 13],
       [14, 15],
       [15, 16],
       [17, 18],
       [18, 19],
       [20, 21]])

In [50]:
np.zeros([3,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [106]:
e=np.arange(20)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [109]:
e.reshape(2,2,-3)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [111]:
z=np.arange(18)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [112]:
z.reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [113]:
# 2d array
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
n[n>2]

array([3, 4, 5, 6, 7, 8, 9])

In [115]:
n>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [116]:
# subset
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
b=a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [126]:
b[11]=100
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [127]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [129]:
# memory
np.shares_memory(a,b)

True

In [133]:
a1=np.arange(12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [134]:
b1=a1.copy()
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
b1[11]=100
b1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [136]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
# memory
np.shares_memory(a1,b1)

False

In [138]:
# transpose of a matrix
t=np.array([[10,20,30],[40,50,60]])
t

array([[10, 20, 30],
       [40, 50, 60]])

In [140]:
t.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [141]:
x=np.array([[100,200,300,400],[500,600,700,800]])
x

array([[100, 200, 300, 400],
       [500, 600, 700, 800]])

In [142]:
x.T

array([[100, 500],
       [200, 600],
       [300, 700],
       [400, 800]])

In [143]:
# vertical stack and horizontal stack
u=np.array([[11,22,33,44],[44,55,66,77]])
u

array([[11, 22, 33, 44],
       [44, 55, 66, 77]])

In [144]:
v=np.array([[10,20,30,40],[40,50,60,70]])
v

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [146]:
np.vstack([u,v])

array([[11, 22, 33, 44],
       [44, 55, 66, 77],
       [10, 20, 30, 40],
       [40, 50, 60, 70]])

In [147]:
np.hstack([u,v])

array([[11, 22, 33, 44, 10, 20, 30, 40],
       [44, 55, 66, 77, 40, 50, 60, 70]])

In [148]:
# some other mathematical operations
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [154]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [155]:
np.sum(a)

45

In [156]:
np.median(a)

5.0

In [159]:
a.std()

2.581988897471611

In [167]:
# dot and cross product
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
b=a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [170]:

np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [171]:
np.cross(a,b)

array([[  2,  -4,   2],
       [ 10, -20,  10],
       [ 18, -36,  18]])

In [172]:
# boolean
x=np.array([1,1,0],dtype=bool)
y=np.array([1,0,1],dtype=bool)
print(x)
print(y)

[ True  True False]
[ True False  True]


In [173]:
# logical or,and 
np.logical_or(x,y)


array([ True,  True,  True])

In [174]:
np.logical_and(x,y)

array([ True, False, False])

In [176]:
# any and all
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [177]:
np.all(a==a)

True

In [178]:
np.all(a>2)

False

In [180]:
np.all(a>=1)

True

In [181]:
np.any(a==7)

True

In [183]:
n=np.array([[1,2,3],[4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
n.sum()

21

In [187]:
n.sum(axis=0)

array([5, 7, 9])

In [188]:
n.sum(axis=1)

array([ 6, 15])

In [189]:
n.max()

6

In [190]:
n.min()

1

In [191]:
n.argmax()

5

In [192]:
n.argmin()

0

In [202]:
# sort and argsort
s=np.array([[3,5,9,7,1,3,1,4],[2,4,8,6,7,3,1,4]])
s

array([[3, 5, 9, 7, 1, 3, 1, 4],
       [2, 4, 8, 6, 7, 3, 1, 4]])

In [203]:
np.sort(s)

array([[1, 1, 3, 3, 4, 5, 7, 9],
       [1, 2, 3, 4, 4, 6, 7, 8]])

In [204]:
np.argsort(s)

array([[4, 6, 0, 5, 7, 1, 3, 2],
       [6, 0, 5, 1, 7, 3, 4, 2]], dtype=int64)